# Generated by Django 4.0.3 on 2022-04-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
