# Generated by Django 4.0.3 on 2022-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='document',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
