# Generated by Django 4.0.3 on 2022-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
